### ISSUE TITLE
skip broken option

### ISSUE THREAD

**Issue by mpuel** [antoineco/aco-yum_autoupdate#11]
Hello,

I am using your module smoothly for some time now. I am encountering an issue while our update policy excludes some packages from the update. As some dependencies of this package are updatable, yum-cron fails to update those dependencies and as skip_broken option is not configurable, does not update anything at all.

Would you please add the support for skip_broken option in the module ?

Best regards,

**Comment by antoineco** [comment]
Sounds reasonable, I'll add this asap

**Comment by mpuel** [comment]
Thanks for the merge, I am checking ASAP.
